### ISSUE TITLE
安装后yarn dev报错

### ISSUE THREAD

**Issue by Myeeoo** [xiaoxian521/pure-admin-backend#1]
(base) yangqing@yangqingdeMac-mini adminbk-main % yarn dev
yarn run v1.22.19
$ ts-node ./src/server.ts
/opt/homebrew/lib/node_modules/ts-node/src/index.ts:859
return new TSError(diagnosticText, diagnosticCodes, diagnostics);
^
TSError: ⨯ Unable to compile TypeScript:
src/server.ts:22:5 - error TS2339: Property 'post' does not exist on type 'Application'.

22 app.post("/login", (req, res) => {
~~~~
src/server.ts:26:5 - error TS2339: Property 'post' does not exist on type 'Application'.

26 app.post("/register", (req, res) => {
~~~~
src/server.ts:30:5 - error TS2339: Property 'put' does not exist on type 'Application'.

30 app.put("/updateList/:id", (req, res) => {
~~~
src/server.ts:34:5 - error TS2339: Property 'delete' does not exist on type 'Application'.

34 app.delete("/deleteList/:id", (req, res) => {
~~~~~~
src/server.ts:38:5 - error TS2339: Property 'post' does not exist on type 'Application'.

38 app.post("/searchPage", (req, res) => {
~~~~
src/server.ts:42:5 - error TS2339: Property 'post' does not exist on type 'Application'.

42 app.post("/searchVague", (req, res) => {
~~~~
src/server.ts:46:5 - error TS2339: Property 'get' does not exist on type 'Application'.

46 app.get("/captcha", (req, res) => {
~~~
src/server.ts:51:4 - error TS2339: Property 'listen' does not exist on type 'Application'.

51 .listen(config.port, () => {
~~~~~~

at createTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:859:12)
at reportTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:863:19)
at getOutput (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1077:36)
at Object.compile (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1433:41)
at Module.m._compile (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1617:30)
at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
at Object.require.extensions.<computed> [as .ts] (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1621:12)
at Module.load (node:internal/modules/cjs/loader:997:32)
at Function.Module._load (node:internal/modules/cjs/loader:838:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
diagnosticCodes: [
2339, 2339, 2339,
2339, 2339, 2339,
2339, 2339
]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by xiaoxian521** [comment]
需要打开mysql数据库 并连接 具体看视频教程

**Comment by Myeeoo** [comment]
> 需要打开mysql数据库并连接具体看视频教程
我没有找到后端的教程！是在[vue-pure-admin]的教程里么？？

**Comment by xiaoxian521** [comment]
是的 b站上 具体哪一节我忘了

**Comment by Myeeoo** [comment]
谢谢大佬，我找一下！！
